import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import "./globals.css";
import NextAuthSessionProvider from "./components/SessionProvider";
import ConditionalNavbar from "./components/ConditionalNavbar";
import Footer from "./components/Footer";
import Toaster from "./components/Toaster";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CareConnect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <div className="w-full min-h-screen flex flex-col">
            <ConditionalNavbar />
            <main className="w-full flex-1">
              {children}
            </main>
            <Footer />
          </div>
          <Toaster />
        </NextAuthSessionProvider>
        <Analytics />
      </body>
    </html>
  );
}
